eureka:
  instance:
    hostname: discoveryserver
  client:
    service-url:
      defaultZone: http://discoveryserver:8777/eureka
    instance:
      preferIpAddress: true

server:
  port: 8666

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-microservice
          uri: http://usermicroservice:8555
          predicates:
            - Path=/api/v1/auth/register, /api/v1/auth/login , /api/v1/auth/verifyUser/** , /api/v1/auth/refresh
        - id: auth-microservice
          uri: http://usermicroservice:8555
          predicates:
            - Path=/api/v1/auth/logout
          filters:
            - JwtAuthFilter
        - id: user-microservice
          uri: http://usermicroservice:8555
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthFilter
        - id: flight-microservice
          uri: http://flightmicroservice:8444
          predicates:
            - Path=/api/v1/flights/**
          filters:
            - JwtAuthFilter
        - id: ticket-microservice
          uri: http://ticketmicroservice:8333
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - JwtAuthFilter
        - id: payment-microservice
          uri: http://paymentmicroservice:8222
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - JwtAuthFilter

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

api:
  secretkey: ${SECRET_KEY}
  urls:
    authUrl: http://apigateway:8666/api/v1/auth