eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8777/eureka

server:
  port: 8333

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/ticketsdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql

#set your own 256-bit secret key
api:
  secretkey:
  urls:
    flightUrl: http://localhost:8666/api/v1/flights
    userUrl: http://localhost:8666/api/v1/users
    paymentUrl: http://localhost:8666/api/v1/payments