eureka:
  instance:
    hostname: discoveryserver
  client:
    service-url:
      defaultZone: http://discoveryserver:8777/eureka
    instance:
      preferIpAddress: true

server:
  port: 8555

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/usersdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

#Duration of the access token in milliseconds
expire:
  access-token: ${ACCESS_TOKEN_EXPIRE}
  refresh-token: ${REFRESH_TOKEN_EXPIRE}

#set your own 256-bit secret key
api:
  secretkey: ${SECRET_KEY}
