eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8777/eureka

server:
  port: 8555

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/usersdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9422/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

#Duration of the access token in milliseconds
expire:
  jw-token: 3600000

#set your own 256-bit secret key
api:
  secretkey:
